package gg.babble.babble.domain.image;

import gg.babble.babble.domain.FileName;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public enum AutoGeneratedSize {
    X1920(1920),
    X1280(1280),
    X640(640);

    private final int size;

    AutoGeneratedSize(final int size) {
        this.size = size;
    }

    public static List<Integer> getAutoGeneratedSizes() {
        return Arrays.stream(values()).map(value -> value.size).collect(Collectors.toList());
    }
}
