spring:

  datasource:
    url: jdbc:mariadb://172.17.0.2:3306/babble
    driver-class-name: org.mariadb.jdbc.Driver
    username: babble

  jpa:
    hibernate:
      ddl-auto: validate

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket:
        name: babble-back-test
