spring:

  datasource:
    url: jdbc:mariadb://172.17.0.2:3306/babble
    driver-class-name: org.mariadb.jdbc.Driver
    username: babble

  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB
      location: ${java:io:tmpdir}

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket:
        name: bucket-babble-front-test
