spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.7:3306/babble
    username: babble

  jpa:
    hibernate:
      ddl-auto: validate

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket:
        name: babble-back-test
