spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.2.215:3306/babble
    username: babble

    slaves:
      slave1:
        name: slave1
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://192.168.2.235:3306/babble
        username: babble

      slave2:
        name: slave2
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://192.168.2.80:3306/babble
        username: babble

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: false
        generate-ddl: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_sql_comment: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB
      location: ${java:io:tmpdir}

  redis:
    host: 192.168.2.45
    port: 6379

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket:
        name: bucket-babble-front-test
