spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.7:3306/babble
    username: babble

  jpa:
    hibernate:
      ddl-auto: validate

  redis:
    host: 192.168.2.114
    port: 6379

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket:
        name: bucket-babble-front
