spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.2.59:3306/babble
    username: babble

  test:
    database:
      replace: NONE

  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB
      location: ${java:io:tmpdir}

  redis:
    host: 192.168.2.135
    port: 6379

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket:
        name: babble-back-test
