# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Backend release branch CI with gradle

on:
  push:
    branches: [ release ]
    paths:
      - 'back/**'

jobs:
  deploy-build:
    runs-on: deploy

    steps:
    - uses: actions/checkout@v2
    - name: JDK 8 버전으로 변경
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: gradlew 권한 변경
      working-directory: ./back/babble
      run: chmod +x gradlew

    - name: Web Application Server 빌드 진행
      working-directory: ./back/babble
      run: SPRING_DATASOURCE_PASSWORD=${{ secrets.JUNIT_DB_PASSWORD }} SPRING_REDIS_PASSWORD=${{ secrets.SPRING_REDIS_PASSWORD }} ./gradlew build

    - name: JDK 11 버전으로 변경
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: SonarQube 빌드 진행
      working-directory: ./back/babble
      run: SPRING_PROFILES_ACTIVE=local ./gradlew sonarqube -Dsonar.projectKey=babble-sonarqube -Dsonar.host.url=${{ secrets.SONARQUBE_SERVER_URL }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

    - name: jar 파일 복사
      working-directory: ./back
      run: cp ./babble/build/libs/babble-0.0.1-SNAPSHOT.jar ./deploy/was

    - name: 도커 이미지 빌드
      working-directory: ./back/deploy/was
      run: docker build -t babble-was:latest .

    - name: 도커 이미지 태그 추가
      working-directory: ./back/deploy/was
      run: docker tag babble-was:latest 2021babble/babble-was:latest

    - name: 도커 이미지 배포
      working-directory: ./back/deploy/was
      run: docker push 2021babble/babble-was:latest
    
    - name: 도커 서비스 롤링 업데이트
      run: ssh test-was-manager "docker pull 2021babble/babble-was:latest; docker service update --image 2021babble/babble-was:latest babble-was;"
      