# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    paths:
      - 'back/**'

jobs:
  deploy-build:
    runs-on: deploy

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: gradlew 권한 변경
      working-directory: ./back/babble
      run: chmod +x gradlew

    - name: 빌드 진행
      working-directory: ./back/babble
      run: ./gradlew build

    - name: SCP 명령을 이용해 WAS 서버로 jar 파일 전송
      working-directory: ./back/babble
      run: scp ./build/libs/babble-0.0.1-SNAPSHOT.jar was:/home/ubuntu

    - name: SSH 명령을 통해 WAS 서버 접속 후 jar 파일 실행
      run: ssh was "/home/ubuntu/deploy/deploy.sh"

  sonarqube-build:
    runs-on: deploy
    needs: deploy-build

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: gradlew 권한 변경
      working-directory: ./back/babble
      run: chmod +x gradlew

    - name: 소나큐브 빌드 진행
      working-directory: ./back/babble
      run: ./gradlew sonarqube -Dsonar.projectKey=babble-sonarqube -Dsonar.host.url=${{ secrets.SONARQUBE_SERVER_URL }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
