name: Node.js Package

on:
  push:
    branches: [release]
    paths:
      - 'front/**'

jobs:
  build:
    runs-on: deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: 패키지 설치
        working-directory: ./front
        run: npm install

      - name: 빌드
        working-directory: ./front
        run: npm run prod

      - name: 배포
        working-directory: ./front
        run: aws s3 sync ./dist s3://bucket-babble-front-test/

      - name: 캐시 무효화
        working-directory: ./front
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/index.html" "/bundle.js"
