name: Node.js Package

on:
  push:
    branches: [release]
    paths:
      - "/front/**"

jobs:
  build:
    runs-on: deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: 패키지 설치
        working-directory: ./front
        run: npm install

      - name: 빌드
        working-directory: ./front
        run: npm run prod

      - name: Semantic Release 실행
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 16
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branches: |
            ['release']
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm install && NPM_TOKEN=$NPM_TOKEN GH_TOKEN=$GH_TOKEN npx semantic-release --branches=release

      - name: 배포
        working-directory: ./front
        run: aws s3 sync ./dist s3://bucket-babble-front/
